### ISSUE TITLE
Crear carpeta 'runs' en la VM

### ISSUE THREAD

**Issue by dmacha27** [msp1015/TFG-Semi-Supervised-Learning#53]
No existe carpeta 'runs' en el servidor y no se almacenan las ejecuciones. Para evitar esto se podría incluir una línea de código que cree esas carpetas (datasets/{anonimos,registrados} y runs) cada vez que se levanta la web.

**Comment by msp1015** [comment]
Arreglado, había creado la carpeta runs pero en ./web en vez de ./web/app. Con resetear el servicio que corre la app es suficiente cada vez que haya un cambio.

Gracias por avisar!!
