### ISSUE TITLE
Doc Anexo E: Manual de usuario

### ISSUE THREAD

**Issue by msp1015** [msp1015/TFG-Semi-Supervised-Learning#56]
Crear el nuevo manual de usuario de la aplicación.

@alvarag Entiendo que en el caso del manual si que debo copiar el que hizo David tal cual y poner todo lo nuevo?

**Comment by msp1015** [comment]
Vuelvo a comentar que probablemente no lo has visto, @alvarag

**Comment by alvarag** [comment]
Disculpa, se me pasó efectivamente. Pues en el manual de usuario yo creo que sí: pon todo lo que tenía David más lo nuevo tuyo y cambias la pantalla principal y todas las que hayan cambiado. Así puedes luego anexar ese PDF como ayuda (al igual que estaba antes)
