### ISSUE TITLE
Doc anexo D: Manual del programador

### ISSUE THREAD

**Issue by msp1015** [msp1015/TFG-Semi-Supervised-Learning#57]
Documentar manual del programador:

- [x] Introducción
- [x] Estructura de directorios
- [x] Manual del programador
- [x] Compilacion, instalacion y ejecucion del proyecto
- [x] Pruebas del sistema

**Comment by alvarag** [comment]
Comentarios en los anexos

[anexos-AAG.pdf](https://github.com/user-attachments/files/16106285/anexos-AAG.pdf)

**Comment by msp1015** [comment]
Lo de la licencia ni había mirado el caso de David, él usa BSD-3-Clause license, que por lo que veo es parecido en cuanto a permisos, pongo la suya o dejo MIT?

**Comment by alvarag** [comment]
Me temo que tendrás que arrastrar la suya pues no habría justificación para cambiarla siendo un desarollo sobre el de David
